"""Create Statistics table

Revision ID: 3fcb1832636a
Revises: 5d1852b8bfa5
Create Date: 2024-12-21 16:34:36.745184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcb1832636a'
down_revision = '5d1852b8bfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('choix_X', sa.String(length=255), nullable=False),
    sa.Column('choix_Y', sa.String(length=255), nullable=True),
    sa.Column('filter_type', sa.String(length=255), nullable=True),
    sa.Column('filter_value', sa.String(length=255), nullable=True),
    sa.Column('library', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('column', sa.String(length=255), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('quartiles', sa.String(length=255), nullable=True),
    sa.Column('skewness', sa.Float(), nullable=True),
    sa.Column('kurtosis', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_table('charts')
    # ### end Alembic commands ###
